version: '2'
services:
  postgres:
    image: postgres
  clamd:
    image: dinkel/clamavd
  backend:
    build: .
    depends_on:
      - postgres
      - clamd
    ports:
      - "3000:3000"
    volumes:
      - log:/app/src/log
    environment:
      DATABASE_TIMEOUT: 120
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: product-review-platform_test
      DATABASE_SERVICE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 
      SECRET_KEY_BASE: 6bea67b73e3305b110901e4ccd35636f30a115a0b639aebc78e75fd00309e028154335b10cca7c943a2108176059e2e4c0e707b526d27c06f71ffd2cf8b37e79
      RAILS_ENV: test

volumes:
  log: {}